<html>
	<head>
		<title>Prueba Header</title>
		<script type="text/javascript" src="//resourcesuat.personal.com.ar/components/jquery/jquery-1.11.1.min.js"></script>
		<script type="text/javascript" src="//resourcesuat.personal.com.ar/components/tpinjector/v1/tpinjector.js"></script>
	</head>
	<body>
		<p>Hola esto es una prueba</p>
		<script type="text/javascript" src="//resourcesuat.personal.com.ar/components/jquery/jquery-1.11.1.min.js"></script>
		<script type="text/javascript" src="//resourcesuat.personal.com.ar/components/tpinjector/v1/tpinjector.js"></script>
	</body>
</html>